# Generated by Django 4.1 on 2022-09-03 14:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MissingPerson',
            fields=[
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('missing_circumstances', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(max_length=20)),
                ('Police_station', models.CharField(max_length=200)),
                ('station_number', models.CharField(max_length=12)),
                ('e_mail', models.CharField(max_length=200)),
                ('missing_date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
