# Generated by Django 4.1 on 2022-09-03 17:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_missingperson_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('crime', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WantedPerson',
            fields=[
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('aliases', models.CharField(default='unknown', max_length=200)),
                ('crime_circumstances', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('Police_station', models.CharField(max_length=200)),
                ('station_number', models.CharField(max_length=12)),
                ('e_mail', models.CharField(max_length=200)),
                ('crime_date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tags', models.ManyToManyField(blank=True, to='base.tag')),
            ],
        ),
    ]
