# Generated by Django 4.1 on 2022-09-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_wantedperson_crime_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='wantedperson',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
